# Generated by Django 4.1.7 on 2023-04-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='addition_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
